services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - MONGO_URL=mongodb://root:password@db:27017/
    volumes:
      - ./src:/app/src
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - 27017:27017
    restart: always

networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
    driver: local
